	spring.data.mongodb.uri=mongodb://${MONGO_USER:root}:${MONGO_PASS:root}@localhost:27017/workshop_mongodb?authSource=admin
	logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
	
	spring.main.banner-mode=off
	
	
